<a href="https://colab.research.google.com/github/fboldt/aulasml/blob/master/aula06a_Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!unzip titanic.zip

Archive:  titanic.zip
  inflating: gender_submission.csv
  inflating: test.csv
  inflating: train.csv

In [2]:
import pandas as pd

df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [11]:
y = df['Survived']
X = df.drop('Survived', axis=1)

In [12]:
len(y)

891

In [13]:
for col in X.columns:
  print(f"{col:>12} {len(set(X[col])):4} {X[col].dtype}")

 PassengerId  891 int64
      Pclass    3 int64
        Name  891 object
         Sex    2 object
         Age  265 float64
       SibSp    7 int64
       Parch    7 int64
      Ticket  681 object
        Fare  248 float64
       Cabin  148 object
    Embarked    4 object

In [14]:
caracterriscas_indesejadas = ['PassengerId', 'Name', 'Ticket', 'Cabin']
Xdrop = X.drop(caracterriscas_indesejadas, axis=1)
Xdrop.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [16]:
Xnum = Xdrop.select_dtypes(include='number')
Xnum.columns

Index(['Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [17]:
for col in Xnum.columns:
  print(f"{col:>12} {X[col].isnull().sum():4}")

      Pclass    0
         Age  177
       SibSp    0
       Parch    0
        Fare    0

In [19]:
Xnum[-5:]

     Pclass   Age  SibSp  Parch   Fare
886       2  27.0      0      0  13.00
887       1  19.0      0      0  30.00
888       3   NaN      1      2  23.45
889       1  26.0      0      0  30.00
890       3  32.0      0      0   7.75

In [20]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')
XnumTratado = imputer.fit_transform(Xnum)
XnumTratado[-5:]

array([[ 2.  , 27.  ,  0.  ,  0.  , 13.  ],
       [ 1.  , 19.  ,  0.  ,  0.  , 30.  ],
       [ 3.  , 28.  ,  1.  ,  2.  , 23.45],
       [ 1.  , 26.  ,  0.  ,  0.  , 30.  ],
       [ 3.  , 32.  ,  0.  ,  0.  ,  7.75]])

In [21]:
Xcat = Xdrop.select_dtypes(object)
Xcat.columns

Index(['Sex', 'Embarked'], dtype='object')

In [22]:
for col in Xcat.columns:
  print(f"{col:>12} {X[col].isnull().sum():4}")

         Sex    0
    Embarked    2

In [23]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')
XcatTratado = imputer.fit_transform(Xcat)
XcatTratado[-5:]

array([['male', 'S'],
       ['female', 'S'],
       ['female', 'S'],
       ['male', 'C'],
       ['male', 'Q']], dtype=object)

In [24]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
XcatTratadoHot = encoder.fit_transform(XcatTratado)
XcatTratadoHot

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1782 stored elements and shape (891, 5)>

In [25]:
XcatTratadoHot.toarray()[-5:]

array([[0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [26]:
import numpy as np
Xtratado = np.c_[XnumTratado, XcatTratadoHot.toarray()]
print(Xtratado.shape)
Xtratado[-5:]

(891, 10)

array([[ 2.  , 27.  ,  0.  ,  0.  , 13.  ,  0.  ,  1.  ,  0.  ,  0.  ,
         1.  ],
       [ 1.  , 19.  ,  0.  ,  0.  , 30.  ,  1.  ,  0.  ,  0.  ,  0.  ,
         1.  ],
       [ 3.  , 28.  ,  1.  ,  2.  , 23.45,  1.  ,  0.  ,  0.  ,  0.  ,
         1.  ],
       [ 1.  , 26.  ,  0.  ,  0.  , 30.  ,  0.  ,  1.  ,  1.  ,  0.  ,
         0.  ],
       [ 3.  , 32.  ,  0.  ,  0.  ,  7.75,  0.  ,  1.  ,  0.  ,  1.  ,
         0.  ]])

In [27]:
from sklearn.base import BaseEstimator, TransformerMixin

class AtributosDesejados(BaseEstimator, TransformerMixin):
  def __init__(self):
    self.colunas_indesejadas = ['PassengerId', 'Name', 'Ticket', 'Cabin']
  def fit(self, X, y=None):
    return self
  def transform(self, X, y=None):
    return X.drop(self.colunas_indesejadas, axis=1)

atributos_desejados = AtributosDesejados()
Xdrop = atributos_desejados.fit_transform(X)
Xdrop.tail()

     Pclass     Sex   Age  SibSp  Parch   Fare Embarked
886       2    male  27.0      0      0  13.00        S
887       1  female  19.0      0      0  30.00        S
888       3  female   NaN      1      2  23.45        S
889       1    male  26.0      0      0  30.00        C
890       3    male  32.0      0      0   7.75        Q

In [28]:
class AtributosNumericos(BaseEstimator, TransformerMixin):
  def fit(self, X, y=None):
    return self
  def transform(self, X, y=None):
    return X.select_dtypes(include='number')

atributos_numericos = AtributosNumericos()
Xnum = atributos_numericos.fit_transform(Xdrop)
Xnum.tail()

     Pclass   Age  SibSp  Parch   Fare
886       2  27.0      0      0  13.00
887       1  19.0      0      0  30.00
888       3   NaN      1      2  23.45
889       1  26.0      0      0  30.00
890       3  32.0      0      0   7.75

In [31]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

pipenum = Pipeline([
    ('atributos_numericos', AtributosNumericos()),
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
XnumTratado = pipenum.fit_transform(Xdrop)
XnumTratado[-5:]

array([[-0.36936484, -0.18148724, -0.4745452 , -0.47367361, -0.38667072],
       [-1.56610693, -0.79628599, -0.4745452 , -0.47367361, -0.04438104],
       [ 0.82737724, -0.1046374 ,  0.43279337,  2.00893337, -0.17626324],
       [-1.56610693, -0.25833709, -0.4745452 , -0.47367361, -0.04438104],
       [ 0.82737724,  0.20276197, -0.4745452 , -0.47367361, -0.49237783]])

In [32]:
class AtributosCategoricos(BaseEstimator, TransformerMixin):
  def fit(self, X, y=None):
    return self
  def transform(self, X, y=None):
    return X.select_dtypes(object)

atributos_categoricos = AtributosCategoricos()
Xcat = atributos_categoricos.fit_transform(Xdrop)
Xcat.tail()

        Sex Embarked
886    male        S
887  female        S
888  female        S
889    male        C
890    male        Q

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

pipecat = Pipeline([
    ('atributos_categoricos', AtributosCategoricos()),
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder())
])
XcatTratado = pipecat.fit_transform(Xdrop)
XcatTratado.toarray()[-5:]

array([[0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [35]:
from sklearn.pipeline import FeatureUnion

unecaracteristicas = FeatureUnion([
    ('pipenum', pipenum),
    ('pipecat', pipecat)
])
Xtratado = unecaracteristicas.fit_transform(Xdrop)
Xtratado[-5:].toarray()[-5:]

array([[-0.36936484, -0.18148724, -0.4745452 , -0.47367361, -0.38667072,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ],
       [-1.56610693, -0.79628599, -0.4745452 , -0.47367361, -0.04438104,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.82737724, -0.1046374 ,  0.43279337,  2.00893337, -0.17626324,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ],
       [-1.56610693, -0.25833709, -0.4745452 , -0.47367361, -0.04438104,
         0.        ,  1.        ,  1.        ,  0.        ,  0.        ],
       [ 0.82737724,  0.20276197, -0.4745452 , -0.47367361, -0.49237783,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ]])

In [36]:
class DenseTransformer(BaseEstimator, TransformerMixin):
  def fit(self, X, y=None, **fit_params):
    return self
  def transform(self, X, y=None, **fit_params):
    return X.toarray()

preproc = Pipeline([
    ('atributos_desejados', AtributosDesejados()),
    ('unecaracteristicas', unecaracteristicas),
    ('densidade', DenseTransformer())
])
Xtratado = preproc.fit_transform(X)
Xtratado[-5:]

array([[-0.36936484, -0.18148724, -0.4745452 , -0.47367361, -0.38667072,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ],
       [-1.56610693, -0.79628599, -0.4745452 , -0.47367361, -0.04438104,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.82737724, -0.1046374 ,  0.43279337,  2.00893337, -0.17626324,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ],
       [-1.56610693, -0.25833709, -0.4745452 , -0.47367361, -0.04438104,
         0.        ,  1.        ,  1.        ,  0.        ,  0.        ],
       [ 0.82737724,  0.20276197, -0.4745452 , -0.47367361, -0.49237783,
         0.        ,  1.        ,  0.        ,  1.        ,  0.        ]])

In [37]:
from sklearn.ensemble import RandomForestClassifier

clf = Pipeline([
    ('preproc', preproc),
    ('classificador', RandomForestClassifier())
])
clf.fit(X, y)

Pipeline(steps=[('preproc',
                 Pipeline(steps=[('atributos_desejados', AtributosDesejados()),
                                 ('unecaracteristicas',
                                  FeatureUnion(transformer_list=[('pipenum',
                                                                  Pipeline(steps=[('atributos_numericos',
                                                                                   AtributosNumericos()),
                                                                                  ('imputer',
                                                                                   SimpleImputer(strategy='median')),
                                                                                  ('scaler',
                                                                                   StandardScaler())])),
                                                                 ('pipecat',
                                                                  Pipeline(steps=[('atributos_categoricos',
                                                                                   AtributosCategoricos()),
                                                                                  ('imputer',
                                                                                   SimpleImputer(strategy='most_frequent')),
                                                                                  ('encoder',
                                                                                   OneHotEncoder())]))])),
                                 ('densidade', DenseTransformer())])),
                ('classificador', RandomForestClassifier())])

In [39]:
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

y_pred = clf.predict(X)
accuracy_score(y, y_pred)

0.9797979797979798

In [40]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, y, cv=5)
print(scores.mean())
print(scores)

0.8058690603226413
[0.77653631 0.81460674 0.83707865 0.7752809  0.8258427 ]

In [41]:
Xtest = pd.read_csv('test.csv')
Xtest.shape

(418, 11)

In [42]:
y_pred = clf.predict(Xtest)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1])

In [44]:
!head gender_submission.csv

PassengerId,Survived
892,0
893,1
894,0
895,0
896,1
897,0
898,1
899,0
900,1

In [45]:
submission = pd.read_csv('gender_submission.csv')
submission['Survived'] = y_pred
submission.to_csv('submission.csv', index=False)

In [46]:
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

estimators = [
    ('log_reg', LogisticRegression()),
    ('sgd', SGDClassifier()),
    ('knn', KNeighborsClassifier()),
    ('tree', DecisionTreeClassifier()),
    ('rf', RandomForestClassifier()),
    ('et', ExtraTreesClassifier()),
    ('nb', GaussianNB()),
    ('svm', SVC()),
    ('mlp', MLPClassifier()),
    ('lda', LinearDiscriminantAnalysis())
]


results = {
    'model': [],
    'accuracy_mean': [],
    'accuracy_std': []
}

for est in estimators:
  clf = Pipeline([
      ('preproc', preproc),
      ('classificador', est[1])
  ])
  scores = cross_val_score(clf, X, y, cv=5)
  results['model'].append(est[0])
  results['accuracy_mean'].append(scores.mean())
  results['accuracy_std'].append(scores.std())
  print(f"{est[0]:>5} {scores.mean():.2f} {scores.std():.2f}")

log_reg 0.79 0.02
  sgd 0.70 0.09
  knn 0.81 0.02
 tree 0.77 0.03
   rf 0.81 0.02
   et 0.79 0.03
   nb 0.79 0.01
  svm 0.83 0.02
  mlp 0.83 0.03
  lda 0.79 0.02

In [47]:
!pip install optuna -qq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.4/442.4 kB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.7/268.7 kB 14.7 MB/s eta 0:00:00

In [49]:
from multiprocessing import Pipe
from sklearn.base import BaseEstimator, ClassifierMixin
import optuna
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score

class OptunaSVM(BaseEstimator, ClassifierMixin):
  def __init__(self, n_trials=20):
    self.n_trials = n_trials
  def fit(self, X, y=None):
    def objective(trial):
      C = trial.suggest_float('C', 1e-10, 1e10, log=True)
      gamma = trial.suggest_float('gamma', 1e-10, 1e10, log=True)
      clf = SVC(C=C, gamma=gamma)
      pipe = Pipeline([
          ('preproc', preproc),
          ('classificador', clf)
      ])
      scores = cross_val_score(pipe, X, y, cv=5)
      return scores.mean()
    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=self.n_trials)
    self.model = Pipeline([
        ('preproc', preproc),
        ('classificador', SVC(**study.best_params))
    ])
    self.model.fit(X, y)
    return self
  def predict(self, X, y=None):
    return self.model.predict(X)
  def score(self, X, y):
    return self.model.score(X, y)

model = OptunaSVM(n_trials=20)
scores = cross_val_score(model, X, y, cv=5)
print(scores.mean())
print(scores)

[I 2026-09-28 23:37:30,396] A new study created in memory with name: no-name-d0a6febf-f179-46e6-bdfe-8d940b3cbcd5
[I 2026-09-28 23:41:05,980] Trial 0 finished with value: 0.7430808627991726 and parameters: {'C': 39349881.29703093, 'gamma': 0.2030894744093545}. Best is trial 0 with value: 0.7430808627991726.
[I 2026-09-28 23:41:09,706] Trial 1 finished with value: 0.8173643258150299 and parameters: {'C': 6839416217.748378, 'gamma': 5.332026525126929e-05}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:10,020] Trial 2 finished with value: 0.6137496306510392 and parameters: {'C': 79864.33972411069, 'gamma': 1063951.2243997543}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:10,357] Trial 3 finished with value: 0.6137496306510392 and parameters: {'C': 13983160.578798756, 'gamma': 673178.2168024845}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:10,578] Trial 4 finished with value: 0.8005318625036935 and parameters: {'C': 205.03475326916956, 'gamma': 0.07159064384392069}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:10,727] Trial 5 finished with value: 0.602531271545356 and parameters: {'C': 19.535786240169987, 'gamma': 1.109015607975881e-10}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:11,849] Trial 6 finished with value: 0.6067270757411602 and parameters: {'C': 9148667.791215317, 'gamma': 1005.9303780097395}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:12,014] Trial 7 finished with value: 0.602531271545356 and parameters: {'C': 6.587868245752224e-06, 'gamma': 10.040012046048904}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:12,178] Trial 8 finished with value: 0.602531271545356 and parameters: {'C': 9.122090156554433e-07, 'gamma': 2.39240112079933e-09}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:12,407] Trial 9 finished with value: 0.6123411799468138 and parameters: {'C': 0.20903072137542028, 'gamma': 70.69957605453378}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:12,579] Trial 10 finished with value: 0.602531271545356 and parameters: {'C': 0.02697148930588755, 'gamma': 9.853287745260059e-06}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:12,745] Trial 11 finished with value: 0.7724219442529302 and parameters: {'C': 3433213001.012185, 'gamma': 9.002875082650032e-09}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:12,929] Trial 12 finished with value: 0.7780261991529598 and parameters: {'C': 1636.246231910579, 'gamma': 1.0250528855289526e-05}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:13,138] Trial 13 finished with value: 0.602531271545356 and parameters: {'C': 0.00024812061726159785, 'gamma': 838329413.5817369}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:13,314] Trial 14 finished with value: 0.602531271545356 and parameters: {'C': 1.7963646415421745e-10, 'gamma': 2.6975703607603907e-05}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:13,487] Trial 15 finished with value: 0.8159952723333005 and parameters: {'C': 43.75521742938169, 'gamma': 0.04646255793320398}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:13,672] Trial 16 finished with value: 0.602531271545356 and parameters: {'C': 2.149330084689561e-09, 'gamma': 376680.9190530076}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:13,861] Trial 17 finished with value: 0.7963360583078892 and parameters: {'C': 0.4585262822140116, 'gamma': 0.008617378786330397}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:14,027] Trial 18 finished with value: 0.7850586033684624 and parameters: {'C': 554895.6974362815, 'gamma': 5.807123917597354e-08}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:14,262] Trial 19 finished with value: 0.6137496306510392 and parameters: {'C': 25.052302357382324, 'gamma': 1755095.8288259953}. Best is trial 1 with value: 0.8173643258150299.
[I 2026-09-28 23:41:14,840] A new study created in memory with name: no-name-2665ec7e-ff05-49f8-9d2c-3f4432c5ce23
[I 2026-09-28 23:41:15,005] Trial 0 finished with value: 0.7769920220624447 and parameters: {'C': 10566.002429017433, 'gamma': 8.204072971637878e-07}. Best is trial 0 with value: 0.7769920220624447.
[I 2026-09-28 23:41:15,238] Trial 1 finished with value: 0.6437506155816014 and parameters: {'C': 0.26993826539261484, 'gamma': 1208.201914591964}. Best is trial 0 with value: 0.7769920220624447.
[I 2026-09-28 23:41:15,432] Trial 2 finished with value: 0.7825864276568502 and parameters: {'C': 12311.80118220515, 'gamma': 2.2622580606473096e-06}. Best is trial 2 with value: 0.7825864276568502.
[I 2026-09-28 23:41:15,609] Trial 3 finished with value: 0.7685905643652122 and parameters: {'C': 1021476701.9120233, 'gamma': 5.753378734116517e-07}. Best is trial 2 with value: 0.7825864276568502.
[I 2026-09-28 23:41:15,825] Trial 4 finished with value: 0.631143504382941 and parameters: {'C': 1.1994981754603205e-08, 'gamma': 488855.73631681036}. Best is trial 2 with value: 0.7825864276568502.
[I 2026-09-28 23:41:16,030] Trial 5 finished with value: 0.631143504382941 and parameters: {'C': 6.858110814586722e-06, 'gamma': 418076.8222222778}. Best is trial 2 with value: 0.7825864276568502.
[I 2026-09-28 23:41:16,239] Trial 6 finished with value: 0.631143504382941 and parameters: {'C': 3.26461694175446e-05, 'gamma': 258.67892964842224}. Best is trial 2 with value: 0.7825864276568502.
[I 2026-09-28 23:41:16,446] Trial 7 finished with value: 0.6577563281788634 and parameters: {'C': 11976965.507223336, 'gamma': 1031199.3829538075}. Best is trial 2 with value: 0.7825864276568502.
[I 2026-09-28 23:41:16,587] Trial 8 finished with value: 0.631143504382941 and parameters: {'C': 1453.4653205231612, 'gamma': 2.9441559058849475e-10}. Best is trial 2 with value: 0.7825864276568502.
[I 2026-09-28 23:41:16,730] Trial 9 finished with value: 0.631143504382941 and parameters: {'C': 0.0029244530784333853, 'gamma': 6.552564780851753e-06}. Best is trial 2 with value: 0.7825864276568502.
[I 2026-09-28 23:41:16,885] Trial 10 finished with value: 0.631143504382941 and parameters: {'C': 6.540543915303719e-10, 'gamma': 3.1552216019220354e-07}. Best is trial 2 with value: 0.7825864276568502.
[I 2026-09-28 23:41:17,131] Trial 11 finished with value: 0.8106569486851176 and parameters: {'C': 15744.982517735705, 'gamma': 0.0002599123604320028}. Best is trial 11 with value: 0.8106569486851176.
[I 2026-09-28 23:41:18,395] Trial 12 finished with value: 0.7853639318428051 and parameters: {'C': 3772.964478978079, 'gamma': 0.06080937952568291}. Best is trial 11 with value: 0.8106569486851176.
[I 2026-09-28 23:46:30,483] Trial 13 finished with value: 0.7025805180734759 and parameters: {'C': 35054362.747473896, 'gamma': 0.8139765765557936}. Best is trial 11 with value: 0.8106569486851176.
[I 2026-09-28 23:46:30,634] Trial 14 finished with value: 0.8317246134147542 and parameters: {'C': 24.97634099500928, 'gamma': 0.04077254139478259}. Best is trial 14 with value: 0.8317246134147542.
[I 2026-09-28 23:46:30,787] Trial 15 finished with value: 0.8176696542893727 and parameters: {'C': 8.39768268259481, 'gamma': 0.027571425128148964}. Best is trial 14 with value: 0.8317246134147542.
[I 2026-09-28 23:46:30,934] Trial 16 finished with value: 0.7881808332512558 and parameters: {'C': 1.742428317719044, 'gamma': 0.8057869154520043}. Best is trial 14 with value: 0.8317246134147542.
[I 2026-09-28 23:46:31,142] Trial 17 finished with value: 0.6507436225746085 and parameters: {'C': 212794.5372949211, 'gamma': 3095704994.450593}. Best is trial 14 with value: 0.8317246134147542.
[I 2026-09-28 23:46:31,324] Trial 18 finished with value: 0.631143504382941 and parameters: {'C': 0.007125871322149486, 'gamma': 0.002866083174431884}. Best is trial 14 with value: 0.8317246134147542.
[I 2026-09-28 23:46:31,784] Trial 19 finished with value: 0.65632817886339 and parameters: {'C': 26274.8984579077, 'gamma': 764.0874833695023}. Best is trial 14 with value: 0.8317246134147542.
[I 2026-09-28 23:46:31,820] A new study created in memory with name: no-name-546da671-fb14-47fd-9273-3239e32cdf32
[I 2026-09-28 23:46:31,973] Trial 0 finished with value: 0.7980104402639614 and parameters: {'C': 664.7760302111363, 'gamma': 0.0009997309401765992}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:33,743] Trial 1 finished with value: 0.5792770609672019 and parameters: {'C': 5812270685.795928, 'gamma': 943.3323756644631}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:33,893] Trial 2 finished with value: 0.7938047867625333 and parameters: {'C': 453.5660062712026, 'gamma': 8.374154521591004e-06}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:34,046] Trial 3 finished with value: 0.6171180931744312 and parameters: {'C': 0.0026088611427382406, 'gamma': 0.000452794711984407}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:34,270] Trial 4 finished with value: 0.6213138973702355 and parameters: {'C': 3603.3863156616353, 'gamma': 47282517.147275016}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:34,426] Trial 5 finished with value: 0.6171180931744312 and parameters: {'C': 1.2917513525754966e-06, 'gamma': 0.3538831619577481}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:34,616] Trial 6 finished with value: 0.6171180931744312 and parameters: {'C': 0.00015010014535821718, 'gamma': 2580.3134045959214}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:34,837] Trial 7 finished with value: 0.6283069043632424 and parameters: {'C': 2.3229399013274725, 'gamma': 24938.86363226225}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:35,002] Trial 8 finished with value: 0.6171180931744312 and parameters: {'C': 3.513407442408604e-08, 'gamma': 2.721386886824912}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:35,134] Trial 9 finished with value: 0.7812272234807447 and parameters: {'C': 162786879.6777892, 'gamma': 4.340650647054562e-08}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:35,331] Trial 10 finished with value: 0.6171180931744312 and parameters: {'C': 7.792895901425547e-09, 'gamma': 2399097835.8560014}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:37,618] Trial 11 finished with value: 0.7868413276863981 and parameters: {'C': 11835.839354472395, 'gamma': 0.015500986815530377}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:37,766] Trial 12 finished with value: 0.6171180931744312 and parameters: {'C': 6.552610788833777, 'gamma': 1.776013285972311e-08}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:37,910] Trial 13 finished with value: 0.7826356741849699 and parameters: {'C': 2813306.1179638286, 'gamma': 7.422598220682605e-07}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:38,048] Trial 14 finished with value: 0.6171180931744312 and parameters: {'C': 3.032181497605847e-07, 'gamma': 2.7838404815480244e-10}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:38,192] Trial 15 finished with value: 0.7853737811484292 and parameters: {'C': 2549.38220778514, 'gamma': 2.6026383721405105e-05}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:38,374] Trial 16 finished with value: 0.6381266620703241 and parameters: {'C': 23.4002408162869, 'gamma': 26.015235870310782}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:38,515] Trial 17 finished with value: 0.6171180931744312 and parameters: {'C': 0.019831238975384375, 'gamma': 2.831403124221406e-08}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:38,663] Trial 18 finished with value: 0.6171180931744312 and parameters: {'C': 7.720876090191027e-07, 'gamma': 4.5298230971226485e-05}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:38,875] Trial 19 finished with value: 0.6227223480744607 and parameters: {'C': 2425952.485061804, 'gamma': 20846042.06129492}. Best is trial 0 with value: 0.7980104402639614.
[I 2026-09-28 23:46:38,914] A new study created in memory with name: no-name-012b2ebe-b698-4241-b635-24c613605af2
[I 2026-09-28 23:46:39,107] Trial 0 finished with value: 0.8092583472865164 and parameters: {'C': 1438716.0281409242, 'gamma': 3.1426361781150846e-06}. Best is trial 0 with value: 0.8092583472865164.
[I 2026-09-28 23:46:39,250] Trial 1 finished with value: 0.6213138973702355 and parameters: {'C': 0.0028534305811400798, 'gamma': 0.022081163061596236}. Best is trial 0 with value: 0.8092583472865164.
[I 2026-09-28 23:46:39,454] Trial 2 finished with value: 0.6324928592534226 and parameters: {'C': 40239.216316408434, 'gamma': 1868327.2997688118}. Best is trial 0 with value: 0.8092583472865164.
[I 2026-09-28 23:46:39,613] Trial 3 finished with value: 0.6213138973702355 and parameters: {'C': 0.005815799860810667, 'gamma': 18.296423291281556}. Best is trial 0 with value: 0.8092583472865164.
[I 2026-09-28 23:46:39,783] Trial 4 finished with value: 0.6213138973702355 and parameters: {'C': 0.0005720178196402667, 'gamma': 9235455.396714099}. Best is trial 0 with value: 0.8092583472865164.
[I 2026-09-28 23:46:39,922] Trial 5 finished with value: 0.6213138973702355 and parameters: {'C': 7.523472280255768e-05, 'gamma': 0.03079426309154042}. Best is trial 0 with value: 0.8092583472865164.
[I 2026-09-28 23:46:40,088] Trial 6 finished with value: 0.6213138973702355 and parameters: {'C': 9.43128838834926e-10, 'gamma': 60.037847589192346}. Best is trial 0 with value: 0.8092583472865164.
[I 2026-09-28 23:46:40,287] Trial 7 finished with value: 0.6339111592632719 and parameters: {'C': 16644.28327283333, 'gamma': 20413474.22328423}. Best is trial 0 with value: 0.8092583472865164.
[I 2026-09-28 23:46:49,649] Trial 8 finished with value: 0.8359204176105584 and parameters: {'C': 1108614.8696619442, 'gamma': 0.0007468151654124924}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:46:49,801] Trial 9 finished with value: 0.6213138973702355 and parameters: {'C': 2.4027554869624597e-07, 'gamma': 4.755356001754739e-10}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:46:49,973] Trial 10 finished with value: 0.6213138973702355 and parameters: {'C': 19.671064807326875, 'gamma': 1.156653146301674e-08}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:46:50,355] Trial 11 finished with value: 0.7953215798286222 and parameters: {'C': 2906614155.074351, 'gamma': 4.374814628588207e-06}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:47:34,168] Trial 12 finished with value: 0.7489116517285532 and parameters: {'C': 316788.1636194203, 'gamma': 0.2555955354673538}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:47:34,375] Trial 13 finished with value: 0.7994385895794346 and parameters: {'C': 7102.274299207907, 'gamma': 6.527927528192921e-06}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:47:34,598] Trial 14 finished with value: 0.746173544765094 and parameters: {'C': 4049193971.2267456, 'gamma': 3.938669213452461e-09}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:47:34,910] Trial 15 finished with value: 0.6324928592534226 and parameters: {'C': 9378862740.054287, 'gamma': 245060.82146750359}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:47:36,157] Trial 16 finished with value: 0.6324436127253028 and parameters: {'C': 5667355.948014279, 'gamma': 94.51748995839723}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:47:36,380] Trial 17 finished with value: 0.6213138973702355 and parameters: {'C': 1.067899105771453e-10, 'gamma': 5859331086.513952}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:47:36,568] Trial 18 finished with value: 0.6213138973702355 and parameters: {'C': 865654.8212249991, 'gamma': 1.1517181441968605e-10}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:47:36,751] Trial 19 finished with value: 0.7994385895794346 and parameters: {'C': 19.94480930539555, 'gamma': 0.000655579513499603}. Best is trial 8 with value: 0.8359204176105584.
[I 2026-09-28 23:47:40,025] A new study created in memory with name: no-name-91816676-9ef1-4556-b8b5-0cf2678a91bc
[I 2026-09-28 23:47:40,247] Trial 0 finished with value: 0.6324928592534226 and parameters: {'C': 1144373574.8249192, 'gamma': 36243.66756947563}. Best is trial 0 with value: 0.6324928592534226.
[I 2026-09-28 23:47:40,401] Trial 1 finished with value: 0.7825470304343544 and parameters: {'C': 2975.5142757429717, 'gamma': 3.0197066138422542e-06}. Best is trial 1 with value: 0.7825470304343544.
[I 2026-09-28 23:47:40,538] Trial 2 finished with value: 0.6086969368659509 and parameters: {'C': 1171.8107934382826, 'gamma': 3.3387285670204106e-10}. Best is trial 1 with value: 0.7825470304343544.
[I 2026-09-28 23:47:40,756] Trial 3 finished with value: 0.6353196099674973 and parameters: {'C': 42.48651300011031, 'gamma': 71798.4017093107}. Best is trial 1 with value: 0.7825470304343544.
[I 2026-09-28 23:47:40,962] Trial 4 finished with value: 0.6198758987491381 and parameters: {'C': 164.82722754258543, 'gamma': 78089897.95865265}. Best is trial 1 with value: 0.7825470304343544.
[I 2026-09-28 23:47:41,099] Trial 5 finished with value: 0.6086969368659509 and parameters: {'C': 0.002739893405945289, 'gamma': 6.8278134490114265e-06}. Best is trial 1 with value: 0.7825470304343544.
[I 2026-09-28 23:47:41,250] Trial 6 finished with value: 0.6086969368659509 and parameters: {'C': 5.684044020072172, 'gamma': 2.6504966828977312e-08}. Best is trial 1 with value: 0.7825470304343544.
[I 2026-09-28 23:48:52,217] Trial 7 finished with value: 0.7630158573820546 and parameters: {'C': 774824.7050778711, 'gamma': 0.06738816144181216}. Best is trial 1 with value: 0.7825470304343544.
[I 2026-09-28 23:48:52,372] Trial 8 finished with value: 0.6086969368659509 and parameters: {'C': 1435058.744517361, 'gamma': 1.225703588746478e-10}. Best is trial 1 with value: 0.7825470304343544.
[I 2026-09-28 23:48:52,529] Trial 9 finished with value: 0.6128927410617552 and parameters: {'C': 1125979.4158651936, 'gamma': 8.041497350955981e-10}. Best is trial 1 with value: 0.7825470304343544.
[I 2026-09-28 23:48:52,715] Trial 10 finished with value: 0.6086969368659509 and parameters: {'C': 2.8646194362152678e-05, 'gamma': 575300387.2394985}. Best is trial 1 with value: 0.7825470304343544.
[I 2026-09-28 23:48:53,969] Trial 11 finished with value: 0.7770412685905643 and parameters: {'C': 6158.536003640296, 'gamma': 0.027963562886011477}. Best is trial 1 with value: 0.7825470304343544.
[I 2026-09-28 23:48:54,214] Trial 12 finished with value: 0.7867625332414063 and parameters: {'C': 1486.5051261752233, 'gamma': 0.0007373887669563022}. Best is trial 12 with value: 0.7867625332414063.
[I 2026-09-28 23:48:54,428] Trial 13 finished with value: 0.6086969368659509 and parameters: {'C': 6.033985242262633e-06, 'gamma': 799.9588066500472}. Best is trial 12 with value: 0.7867625332414063.
[I 2026-09-28 23:51:53,780] Trial 14 finished with value: 0.7545356052398307 and parameters: {'C': 275416230.0517054, 'gamma': 0.0117567856268087}. Best is trial 12 with value: 0.7867625332414063.
[I 2026-09-28 23:51:53,937] Trial 15 finished with value: 0.6086969368659509 and parameters: {'C': 2.592435578871052e-10, 'gamma': 0.010227460386370403}. Best is trial 12 with value: 0.7867625332414063.
[I 2026-09-28 23:51:54,099] Trial 16 finished with value: 0.6283069043632423 and parameters: {'C': 268.1512520184859, 'gamma': 3.5809260059250295e-06}. Best is trial 12 with value: 0.7867625332414063.

0.8024543343167411
[0.81564246 0.81460674 0.78089888 0.76404494 0.83707865]

In [51]:
model = OptunaSVM(n_trials=30)
model.fit(X, y)
y_pred = model.predict(Xtest)
submission = pd.read_csv('gender_submission.csv')
submission['Survived'] = y_pred
submission.to_csv('submission_optuna.csv', index=False)

[I 2026-09-28 23:55:51,105] A new study created in memory with name: no-name-c572e23d-c3fb-4650-bf8d-1f61e230ace8
[I 2026-09-28 23:55:51,418] Trial 0 finished with value: 0.6374678300169482 and parameters: {'C': 173325.3948836307, 'gamma': 3730518.4114332926}. Best is trial 0 with value: 0.6374678300169482.
[I 2026-09-28 23:55:54,346] Trial 1 finished with value: 0.6161257924800703 and parameters: {'C': 437183721.2190712, 'gamma': 1873.6150146031034}. Best is trial 0 with value: 0.6374678300169482.
[I 2026-09-28 23:55:54,596] Trial 2 finished with value: 0.6385851484527023 and parameters: {'C': 5.895898047237088, 'gamma': 762548.5083071947}. Best is trial 2 with value: 0.6385851484527023.
[I 2026-09-29 00:09:03,501] Trial 3 finished with value: 0.6644466762915071 and parameters: {'C': 1358670923.3326426, 'gamma': 0.8167131659641242}. Best is trial 3 with value: 0.6644466762915071.
[I 2026-09-29 00:09:03,777] Trial 4 finished with value: 0.6374615529470844 and parameters: {'C': 30.19332033548757, 'gamma': 773.0349586282625}. Best is trial 3 with value: 0.6644466762915071.
[I 2026-09-29 00:09:28,752] Trial 5 finished with value: 0.8080597577051034 and parameters: {'C': 12378233.397675822, 'gamma': 0.0004470698269736054}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:29,028] Trial 6 finished with value: 0.7934781244115248 and parameters: {'C': 3594695.924125343, 'gamma': 5.576660955530168e-06}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:29,286] Trial 7 finished with value: 0.6161634548992531 and parameters: {'C': 0.01041504907240284, 'gamma': 3663.833333264071}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:29,516] Trial 8 finished with value: 0.6161634548992531 and parameters: {'C': 7.052090086456149e-07, 'gamma': 34922.61623353311}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:29,739] Trial 9 finished with value: 0.6161634548992531 and parameters: {'C': 6.747179770440816e-10, 'gamma': 132012614.00150141}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:29,899] Trial 10 finished with value: 0.6161634548992531 and parameters: {'C': 3.232969600455986, 'gamma': 6.418972401223682e-09}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:30,094] Trial 11 finished with value: 0.7856192329420627 and parameters: {'C': 257065.10993059227, 'gamma': 3.199252218836421e-06}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:30,268] Trial 12 finished with value: 0.6161634548992531 and parameters: {'C': 1.7710307477609068e-07, 'gamma': 0.00039615306714042923}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:30,425] Trial 13 finished with value: 0.6958885192392191 and parameters: {'C': 70260649.02446544, 'gamma': 7.004067308179642e-10}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:45,078] Trial 14 finished with value: 0.6846525641830393 and parameters: {'C': 106159.65405512536, 'gamma': 2.9410361426585196}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:45,254] Trial 15 finished with value: 0.6161634548992531 and parameters: {'C': 0.25981142537174323, 'gamma': 0.0008939516364056048}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:45,481] Trial 16 finished with value: 0.7890527901575544 and parameters: {'C': 49261974.142685205, 'gamma': 2.54715941271692e-06}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:45,679] Trial 17 finished with value: 0.6161634548992531 and parameters: {'C': 2.097101185589582e-09, 'gamma': 1.450399731711468e-10}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:45,865] Trial 18 finished with value: 0.6161634548992531 and parameters: {'C': 5248.130821681957, 'gamma': 2.2899432730266153e-09}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:46,151] Trial 19 finished with value: 0.6329922792040676 and parameters: {'C': 4999952199.803422, 'gamma': 19697534.315266278}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:46,376] Trial 20 finished with value: 0.7968489109283786 and parameters: {'C': 2292.30879527932, 'gamma': 0.0005078653499087329}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:47,461] Trial 21 finished with value: 0.8025171050153789 and parameters: {'C': 2104.599792654089, 'gamma': 0.05711343951175042}. Best is trial 5 with value: 0.8080597577051034.
[I 2026-09-29 00:09:47,687] Trial 22 finished with value: 0.8215366267026551 and parameters: {'C': 868.0977556045929, 'gamma': 0.002139623107487762}. Best is trial 22 with value: 0.8215366267026551.
[I 2026-09-29 00:09:48,156] Trial 23 finished with value: 0.7744209403050656 and parameters: {'C': 266.34161714012214, 'gamma': 0.26828954464409055}. Best is trial 22 with value: 0.8215366267026551.
[I 2026-09-29 00:09:50,745] Trial 24 finished with value: 0.808097420124286 and parameters: {'C': 9847746902.790857, 'gamma': 2.9062145574622625e-05}. Best is trial 22 with value: 0.8215366267026551.
[I 2026-09-29 00:16:54,449] Trial 25 finished with value: 0.7688092398468396 and parameters: {'C': 281368978.7558766, 'gamma': 0.015108673440738886}. Best is trial 22 with value: 0.8215366267026551.
[I 2026-09-29 00:23:19,169] Trial 26 finished with value: 0.7800765802523383 and parameters: {'C': 8403355277.185653, 'gamma': 0.0036345238435739574}. Best is trial 22 with value: 0.8215366267026551.
[I 2026-09-29 00:23:19,383] Trial 27 finished with value: 0.6161634548992531 and parameters: {'C': 0.0006299507401765174, 'gamma': 658600327.8404979}. Best is trial 22 with value: 0.8215366267026551.
[I 2026-09-29 00:23:19,526] Trial 28 finished with value: 0.7923733601154981 and parameters: {'C': 1581457601.016294, 'gamma': 6.082666961188834e-08}. Best is trial 22 with value: 0.8215366267026551.
[I 2026-09-29 00:23:19,695] Trial 29 finished with value: 0.7160881300608876 and parameters: {'C': 49.15805010437887, 'gamma': 2.5735177958561244e-05}. Best is trial 22 with value: 0.8215366267026551.

In [55]:
class OptunaMLP(BaseEstimator, ClassifierMixin):
  def __init__(self, n_trials=20):
    self.n_trials = n_trials
  def fit(self, X, y=None):
    def objective(trial):
      hidden_layer_size = trial.suggest_int('hidden_layer_size', 50, 500)
      max_iter = trial.suggest_int('max_iter', 100, 1000)
      clf = MLPClassifier(hidden_layer_sizes=(hidden_layer_size, ), max_iter=max_iter)
      pipe = Pipeline([
          ('preproc', preproc),
          ('classificador', clf)
      ])
      scores = cross_val_score(pipe, X, y, cv=5)
      return scores.mean()
    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=self.n_trials)
    print(study.best_params)
    self.model = Pipeline([
        ('preproc', preproc),
        ('classificador', MLPClassifier(
            hidden_layer_sizes=(study.best_params["hidden_layer_size"], ),
            max_iter=study.best_params["max_iter"]))
    ])
    self.model.fit(X, y)
    return self
  def predict(self, X, y=None):
    return self.model.predict(X)
  def score(self, X, y):
    return self.model.score(X, y)

model = OptunaMLP(n_trials=10)
scores = cross_val_score(model, X, y, cv=5)
print(scores.mean())
print(scores)

[I 2026-09-29 00:38:00,565] A new study created in memory with name: no-name-87e7e6c2-013f-4693-9253-2f5ed5095d27
[I 2026-09-29 00:38:02,577] Trial 0 finished with value: 0.8244164286417807 and parameters: {'hidden_layer_size': 126, 'max_iter': 212}. Best is trial 0 with value: 0.8244164286417807.
[I 2026-09-29 00:38:11,275] Trial 1 finished with value: 0.8132177681473456 and parameters: {'hidden_layer_size': 288, 'max_iter': 467}. Best is trial 0 with value: 0.8244164286417807.
[I 2026-09-29 00:38:17,542] Trial 2 finished with value: 0.8075544174135724 and parameters: {'hidden_layer_size': 97, 'max_iter': 842}. Best is trial 0 with value: 0.8244164286417807.
[I 2026-09-29 00:38:19,715] Trial 3 finished with value: 0.8202009258347287 and parameters: {'hidden_layer_size': 109, 'max_iter': 304}. Best is trial 0 with value: 0.8244164286417807.
[I 2026-09-29 00:38:21,745] Trial 4 finished with value: 0.8216093765389539 and parameters: {'hidden_layer_size': 253, 'max_iter': 165}. Best is trial 0 with value: 0.8244164286417807.
[I 2026-09-29 00:38:26,775] Trial 5 finished with value: 0.8061656653205949 and parameters: {'hidden_layer_size': 202, 'max_iter': 452}. Best is trial 0 with value: 0.8244164286417807.
[I 2026-09-29 00:38:47,581] Trial 6 finished with value: 0.8104304146557668 and parameters: {'hidden_layer_size': 401, 'max_iter': 870}. Best is trial 0 with value: 0.8244164286417807.
[I 2026-09-29 00:38:51,705] Trial 7 finished with value: 0.814586821629075 and parameters: {'hidden_layer_size': 102, 'max_iter': 498}. Best is trial 0 with value: 0.8244164286417807.
[I 2026-09-29 00:38:55,237] Trial 8 finished with value: 0.8174037230375258 and parameters: {'hidden_layer_size': 331, 'max_iter': 184}. Best is trial 0 with value: 0.8244164286417807.
[I 2026-09-29 00:38:58,189] Trial 9 finished with value: 0.8244262779474048 and parameters: {'hidden_layer_size': 66, 'max_iter': 508}. Best is trial 9 with value: 0.8244262779474048.

{'hidden_layer_size': 66, 'max_iter': 508}

[I 2026-09-29 00:38:58,945] A new study created in memory with name: no-name-ae2ca018-c336-4a4f-8f7c-13c920a2a1d4
[I 2026-09-29 00:39:01,890] Trial 0 finished with value: 0.8176598049837487 and parameters: {'hidden_layer_size': 82, 'max_iter': 446}. Best is trial 0 with value: 0.8176598049837487.
[I 2026-09-29 00:39:10,826] Trial 1 finished with value: 0.8022259430710135 and parameters: {'hidden_layer_size': 201, 'max_iter': 838}. Best is trial 0 with value: 0.8176598049837487.
[I 2026-09-29 00:39:30,113] Trial 2 finished with value: 0.8050132965625924 and parameters: {'hidden_layer_size': 401, 'max_iter': 676}. Best is trial 0 with value: 0.8176598049837487.
[I 2026-09-29 00:39:50,190] Trial 3 finished with value: 0.800817492366788 and parameters: {'hidden_layer_size': 365, 'max_iter': 952}. Best is trial 0 with value: 0.8176598049837487.
[I 2026-09-29 00:39:56,005] Trial 4 finished with value: 0.819078104993598 and parameters: {'hidden_layer_size': 474, 'max_iter': 160}. Best is trial 4 with value: 0.819078104993598.
[I 2026-09-29 00:40:11,832] Trial 5 finished with value: 0.8092681965921404 and parameters: {'hidden_layer_size': 343, 'max_iter': 741}. Best is trial 4 with value: 0.819078104993598.
[I 2026-09-29 00:40:20,948] Trial 6 finished with value: 0.8064315965724417 and parameters: {'hidden_layer_size': 155, 'max_iter': 989}. Best is trial 4 with value: 0.819078104993598.
[I 2026-09-29 00:40:29,742] Trial 7 finished with value: 0.7994188909681867 and parameters: {'hidden_layer_size': 230, 'max_iter': 757}. Best is trial 4 with value: 0.819078104993598.
[I 2026-09-29 00:40:35,797] Trial 8 finished with value: 0.814852752880922 and parameters: {'hidden_layer_size': 307, 'max_iter': 325}. Best is trial 4 with value: 0.819078104993598.
[I 2026-09-29 00:40:43,120] Trial 9 finished with value: 0.8078597458879149 and parameters: {'hidden_layer_size': 119, 'max_iter': 907}. Best is trial 4 with value: 0.819078104993598.

{'hidden_layer_size': 474, 'max_iter': 160}

[I 2026-09-29 00:40:44,196] A new study created in memory with name: no-name-c682b872-a1f5-46f1-a3f3-54aaf86e919a
[I 2026-09-29 00:41:07,561] Trial 0 finished with value: 0.7854427262877968 and parameters: {'hidden_layer_size': 388, 'max_iter': 947}. Best is trial 0 with value: 0.7854427262877968.
[I 2026-09-29 00:41:14,795] Trial 1 finished with value: 0.8022653402935094 and parameters: {'hidden_layer_size': 182, 'max_iter': 738}. Best is trial 1 with value: 0.8022653402935094.
[I 2026-09-29 00:41:43,373] Trial 2 finished with value: 0.7854328769821727 and parameters: {'hidden_layer_size': 495, 'max_iter': 947}. Best is trial 1 with value: 0.8022653402935094.
[I 2026-09-29 00:42:02,236] Trial 3 finished with value: 0.7826356741849699 and parameters: {'hidden_layer_size': 386, 'max_iter': 794}. Best is trial 1 with value: 0.8022653402935094.
[I 2026-09-29 00:42:04,159] Trial 4 finished with value: 0.8149019994090416 and parameters: {'hidden_layer_size': 220, 'max_iter': 147}. Best is trial 4 with value: 0.8149019994090416.
[I 2026-09-29 00:42:07,311] Trial 5 finished with value: 0.8148823007977939 and parameters: {'hidden_layer_size': 68, 'max_iter': 465}. Best is trial 4 with value: 0.8149019994090416.
[I 2026-09-29 00:42:19,053] Trial 6 finished with value: 0.796641386782232 and parameters: {'hidden_layer_size': 280, 'max_iter': 627}. Best is trial 4 with value: 0.8149019994090416.
[I 2026-09-29 00:42:25,435] Trial 7 finished with value: 0.8050526937850881 and parameters: {'hidden_layer_size': 109, 'max_iter': 842}. Best is trial 4 with value: 0.8149019994090416.
[I 2026-09-29 00:42:30,936] Trial 8 finished with value: 0.8022456416822614 and parameters: {'hidden_layer_size': 97, 'max_iter': 711}. Best is trial 4 with value: 0.8149019994090416.
[I 2026-09-29 00:42:35,388] Trial 9 finished with value: 0.8176795035949965 and parameters: {'hidden_layer_size': 231, 'max_iter': 389}. Best is trial 9 with value: 0.8176795035949965.

{'hidden_layer_size': 231, 'max_iter': 389}

[I 2026-09-29 00:42:36,568] A new study created in memory with name: no-name-61d655b5-e803-4830-9015-5c01265cadcc
[I 2026-09-29 00:42:46,027] Trial 0 finished with value: 0.8078892938047868 and parameters: {'hidden_layer_size': 215, 'max_iter': 826}. Best is trial 0 with value: 0.8078892938047868.
[I 2026-09-29 00:42:47,414] Trial 1 finished with value: 0.8401457697232345 and parameters: {'hidden_layer_size': 92, 'max_iter': 198}. Best is trial 1 with value: 0.8401457697232345.
[I 2026-09-29 00:43:06,515] Trial 2 finished with value: 0.8134935487048164 and parameters: {'hidden_layer_size': 464, 'max_iter': 643}. Best is trial 1 with value: 0.8401457697232345.
[I 2026-09-29 00:43:13,618] Trial 3 finished with value: 0.8135033980104402 and parameters: {'hidden_layer_size': 138, 'max_iter': 865}. Best is trial 1 with value: 0.8401457697232345.
[I 2026-09-29 00:43:16,734] Trial 4 finished with value: 0.8387373190190092 and parameters: {'hidden_layer_size': 236, 'max_iter': 236}. Best is trial 1 with value: 0.8401457697232345.
[I 2026-09-29 00:43:24,256] Trial 5 finished with value: 0.8107061952132375 and parameters: {'hidden_layer_size': 171, 'max_iter': 769}. Best is trial 1 with value: 0.8401457697232345.
[I 2026-09-29 00:43:50,831] Trial 6 finished with value: 0.7980301388752092 and parameters: {'hidden_layer_size': 477, 'max_iter': 928}. Best is trial 1 with value: 0.8401457697232345.
[I 2026-09-29 00:43:54,891] Trial 7 finished with value: 0.8317246134147542 and parameters: {'hidden_layer_size': 204, 'max_iter': 325}. Best is trial 1 with value: 0.8401457697232345.
[I 2026-09-29 00:43:59,355] Trial 8 finished with value: 0.8275091106077023 and parameters: {'hidden_layer_size': 54, 'max_iter': 822}. Best is trial 1 with value: 0.8401457697232345.
[I 2026-09-29 00:44:06,670] Trial 9 finished with value: 0.8135033980104402 and parameters: {'hidden_layer_size': 147, 'max_iter': 737}. Best is trial 1 with value: 0.8401457697232345.

{'hidden_layer_size': 92, 'max_iter': 198}

[I 2026-09-29 00:44:07,010] A new study created in memory with name: no-name-8b9b0a96-5ead-4f82-a274-3bb45f663674
[I 2026-09-29 00:44:09,765] Trial 0 finished with value: 0.7952033881611346 and parameters: {'hidden_layer_size': 353, 'max_iter': 122}. Best is trial 0 with value: 0.7952033881611346.
[I 2026-09-29 00:44:12,549] Trial 1 finished with value: 0.7910174332709543 and parameters: {'hidden_layer_size': 188, 'max_iter': 266}. Best is trial 0 with value: 0.7952033881611346.
[I 2026-09-29 00:44:17,255] Trial 2 finished with value: 0.796621688170984 and parameters: {'hidden_layer_size': 182, 'max_iter': 396}. Best is trial 2 with value: 0.796621688170984.
[I 2026-09-29 00:44:19,435] Trial 3 finished with value: 0.7994090416625628 and parameters: {'hidden_layer_size': 224, 'max_iter': 189}. Best is trial 3 with value: 0.7994090416625628.
[I 2026-09-29 00:44:26,133] Trial 4 finished with value: 0.7882103811681276 and parameters: {'hidden_layer_size': 113, 'max_iter': 895}. Best is trial 3 with value: 0.7994090416625628.
[I 2026-09-29 00:44:47,551] Trial 5 finished with value: 0.7980596867920812 and parameters: {'hidden_layer_size': 182, 'max_iter': 993}. Best is trial 3 with value: 0.7994090416625628.
[I 2026-09-29 00:44:57,872] Trial 6 finished with value: 0.7994287402738107 and parameters: {'hidden_layer_size': 328, 'max_iter': 143}. Best is trial 6 with value: 0.7994287402738107.
[I 2026-09-29 00:45:07,554] Trial 7 finished with value: 0.7910075839653304 and parameters: {'hidden_layer_size': 192, 'max_iter': 879}. Best is trial 6 with value: 0.7994287402738107.
[I 2026-09-29 00:45:14,414] Trial 8 finished with value: 0.7924357332808036 and parameters: {'hidden_layer_size': 425, 'max_iter': 286}. Best is trial 6 with value: 0.7994287402738107.
[I 2026-09-29 00:45:24,018] Trial 9 finished with value: 0.7882793263074952 and parameters: {'hidden_layer_size': 207, 'max_iter': 886}. Best is trial 6 with value: 0.7994287402738107.

{'hidden_layer_size': 328, 'max_iter': 143}
0.8227167158370472
[0.78212291 0.8258427  0.83146067 0.78089888 0.89325843]

In [56]:
model = OptunaMLP(n_trials=30)
model.fit(X, y)
y_pred = model.predict(Xtest)
submission = pd.read_csv('gender_submission.csv')
submission['Survived'] = y_pred
submission.to_csv('submission_optuna_mlp.csv', index=False)

[I 2026-09-29 00:45:24,945] A new study created in memory with name: no-name-b4810cbf-047e-4668-82fb-d9229faa0f01
[I 2026-09-29 00:45:29,739] Trial 0 finished with value: 0.8126043562864854 and parameters: {'hidden_layer_size': 172, 'max_iter': 340}. Best is trial 0 with value: 0.8126043562864854.
[I 2026-09-29 00:45:49,430] Trial 1 finished with value: 0.8092335697696316 and parameters: {'hidden_layer_size': 391, 'max_iter': 531}. Best is trial 0 with value: 0.8126043562864854.
[I 2026-09-29 00:46:10,933] Trial 2 finished with value: 0.8058627832527776 and parameters: {'hidden_layer_size': 383, 'max_iter': 899}. Best is trial 0 with value: 0.8126043562864854.
[I 2026-09-29 00:46:36,779] Trial 3 finished with value: 0.8025359362249702 and parameters: {'hidden_layer_size': 492, 'max_iter': 756}. Best is trial 0 with value: 0.8126043562864854.
[I 2026-09-29 00:46:43,933] Trial 4 finished with value: 0.8159625886636119 and parameters: {'hidden_layer_size': 480, 'max_iter': 178}. Best is trial 4 with value: 0.8159625886636119.
[I 2026-09-29 00:46:49,185] Trial 5 finished with value: 0.812591802146758 and parameters: {'hidden_layer_size': 56, 'max_iter': 918}. Best is trial 4 with value: 0.8159625886636119.
[I 2026-09-29 00:46:52,916] Trial 6 finished with value: 0.8092272926997678 and parameters: {'hidden_layer_size': 131, 'max_iter': 341}. Best is trial 4 with value: 0.8159625886636119.
[I 2026-09-29 00:46:57,982] Trial 7 finished with value: 0.8137279517921036 and parameters: {'hidden_layer_size': 222, 'max_iter': 323}. Best is trial 4 with value: 0.8159625886636119.
[I 2026-09-29 00:47:04,143] Trial 8 finished with value: 0.8170736300295023 and parameters: {'hidden_layer_size': 137, 'max_iter': 577}. Best is trial 8 with value: 0.8170736300295023.
[I 2026-09-29 00:47:14,167] Trial 9 finished with value: 0.8159625886636117 and parameters: {'hidden_layer_size': 296, 'max_iter': 368}. Best is trial 8 with value: 0.8170736300295023.
[I 2026-09-29 00:47:20,648] Trial 10 finished with value: 0.8058502291130502 and parameters: {'hidden_layer_size': 91, 'max_iter': 687}. Best is trial 8 with value: 0.8170736300295023.
[I 2026-09-29 00:47:32,245] Trial 11 finished with value: 0.8137153976523759 and parameters: {'hidden_layer_size': 496, 'max_iter': 288}. Best is trial 8 with value: 0.8170736300295023.
[I 2026-09-29 00:47:35,473] Trial 12 finished with value: 0.8271797125102003 and parameters: {'hidden_layer_size': 334, 'max_iter': 124}. Best is trial 12 with value: 0.8271797125102003.
[I 2026-09-29 00:47:50,947] Trial 13 finished with value: 0.8148452702278576 and parameters: {'hidden_layer_size': 186, 'max_iter': 908}. Best is trial 12 with value: 0.8271797125102003.
[I 2026-09-29 00:48:01,675] Trial 14 finished with value: 0.8047517418868873 and parameters: {'hidden_layer_size': 219, 'max_iter': 625}. Best is trial 12 with value: 0.8271797125102003.
[I 2026-09-29 00:48:02,919] Trial 15 finished with value: 0.8193145439708746 and parameters: {'hidden_layer_size': 131, 'max_iter': 108}. Best is trial 12 with value: 0.8271797125102003.
[I 2026-09-29 00:48:04,518] Trial 16 finished with value: 0.8182035026049841 and parameters: {'hidden_layer_size': 97, 'max_iter': 125}. Best is trial 12 with value: 0.8271797125102003.
[I 2026-09-29 00:48:07,581] Trial 17 finished with value: 0.8226853304877283 and parameters: {'hidden_layer_size': 228, 'max_iter': 126}. Best is trial 12 with value: 0.8271797125102003.
[I 2026-09-29 00:48:10,782] Trial 18 finished with value: 0.8283095850856821 and parameters: {'hidden_layer_size': 290, 'max_iter': 108}. Best is trial 18 with value: 0.8283095850856821.
[I 2026-09-29 00:48:15,031] Trial 19 finished with value: 0.8260812252840374 and parameters: {'hidden_layer_size': 366, 'max_iter': 134}. Best is trial 18 with value: 0.8283095850856821.
[I 2026-09-29 00:48:22,024] Trial 20 finished with value: 0.8159625886636117 and parameters: {'hidden_layer_size': 289, 'max_iter': 223}. Best is trial 18 with value: 0.8283095850856821.
[I 2026-09-29 00:48:25,025] Trial 21 finished with value: 0.8249262444291006 and parameters: {'hidden_layer_size': 345, 'max_iter': 103}. Best is trial 18 with value: 0.8283095850856821.
[I 2026-09-29 00:48:35,727] Trial 22 finished with value: 0.8092398468394955 and parameters: {'hidden_layer_size': 372, 'max_iter': 294}. Best is trial 18 with value: 0.8283095850856821.
[I 2026-09-29 00:48:39,765] Trial 23 finished with value: 0.8193208210407382 and parameters: {'hidden_layer_size': 59, 'max_iter': 482}. Best is trial 18 with value: 0.8283095850856821.
[I 2026-09-29 00:48:53,124] Trial 24 finished with value: 0.8081099742640137 and parameters: {'hidden_layer_size': 354, 'max_iter': 388}. Best is trial 18 with value: 0.8283095850856821.
[I 2026-09-29 00:49:01,791] Trial 25 finished with value: 0.815956311593748 and parameters: {'hidden_layer_size': 301, 'max_iter': 257}. Best is trial 18 with value: 0.8283095850856821.
[I 2026-09-29 00:49:09,717] Trial 26 finished with value: 0.8204506936162199 and parameters: {'hidden_layer_size': 422, 'max_iter': 165}. Best is trial 18 with value: 0.8283095850856821.
[I 2026-09-29 00:49:16,734] Trial 27 finished with value: 0.8159625886636119 and parameters: {'hidden_layer_size': 327, 'max_iter': 192}. Best is trial 18 with value: 0.8283095850856821.
[I 2026-09-29 00:49:35,474] Trial 28 finished with value: 0.8148389931579938 and parameters: {'hidden_layer_size': 463, 'max_iter': 413}. Best is trial 18 with value: 0.8283095850856821.
[I 2026-09-29 00:49:43,814] Trial 29 finished with value: 0.8193333751804657 and parameters: {'hidden_layer_size': 429, 'max_iter': 266}. Best is trial 18 with value: 0.8283095850856821.

{'hidden_layer_size': 290, 'max_iter': 108}